### ISSUE TITLE
Grains prohibits all crafting if workbench is disabled

### ISSUE THREAD

**Issue by chrisbraucker** [pablo3x6/Grains#2]
**Describe the bug**
Installing Grains, and not configuring permissions, disables crafting for normal players (not 'op').
This is likely due to [this](https://github.com/pablo3x6/Grains/blob/857c404817dd906bfa318fabfcde0fdf416ea1b8/src/main/java/si/zbe/grains/events/CraftingLimiter.java#L30) EventHandler that requires the permission `grains.workbench` configured for normal players to craft.
I do think that this is not intended behavior, and should be limited to the portable crafting table.

**To Reproduce**
1. Install Grains
2. Log in as normal player without `grains.workbench` permission

**Expected behavior**
Players should be able to craft.

**OS Data (please complete the following information):**
 - Server version paper-1.17.1-259
 - Plugin version Grains-0.1.2

Thanks for your time, the plugin is very helpful :)

**Comment by zbejas** [comment]
You are right, this was not intended behavior. I am posting an update today with this fixed.

The problem was that I forgot to negate the recipe result check.
